// user
const USER_LOCALSTORAGE_KEY = 'user';
const ACCESS_TOKEN = 'ACCESS_TOKEN';
const REFRESH_TOKEN = 'REFRESH_TOKEN';

// interview
const FILE_NAME = 'interview.mp3';

export { USER_LOCALSTORAGE_KEY, ACCESS_TOKEN, REFRESH_TOKEN, FILE_NAME };
